# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f318e4a4c26c7b9df858a8abf3e350b148c37e5c9d6d87e579b52c01f6f253a6984f745e2127296732dd3dfd655ab6dce98aad0fa7b0d5fb1dd485600a4766d

test:
  secret_key_base: f0cb8f55f27affed0bad869b913e61a82f30054eea9e7f572f77c915fe0d87674b9bef6346ea31ea391919423aad3eaa750911e48a4b05d82b388a0dbf1e806e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
